declare @AnoTemporada int = 2010
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2011
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2012
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2013
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2014
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2015
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2016
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
set @AnoTemporada = 2017
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+RTRIM(LTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno - Verano ' + RTRIM(LTRIM(STR(@AnoTemporada))),'01/01/'+RTRIM(LTRIM(STR(@AnoTemporada))),'31/12/'+RTRIM(LTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),'Invierno  ' + LTRIM(RTRIM(STR(@AnoTemporada))),'25/02/'+LTRIM(RTRIM(STR(@AnoTemporada))),'15/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+LTRIM(RTRIM(CAST(@AnoTemporada as nvarchar(100)))))),LTRIM(RTRIM('Verano ' + LTRIM(RTRIM(STR(@AnoTemporada))) +' - ' +LTRIM(RTRIM(STR(@AnoTemporada+ 1))))),'16/08/'+LTRIM(RTRIM(STR(@AnoTemporada))),'24/02/'+LTRIM(RTRIM(STR(@AnoTemporada+1))),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values('SD','SIN DEFINIR','01/01/1901','31/12/2999',1,getdate(),'SQL Init')
