insert into rubros_cuentas (codigo,nombre,estado,fechaalta,usuarioalta)
values ('ACT','ACTIVO',1,getdate(),'SQL Init')
insert into rubros_cuentas (codigo,nombre,estado,fechaalta,usuarioalta)
values ('PAS','PASIVO',1,getdate(),'SQL Init')
insert into rubros_cuentas (codigo,nombre,estado,fechaalta,usuarioalta)
values ('PNETO','PATRIMONIO NETO',1,getdate(),'SQL Init')
insert into rubros_cuentas (codigo,nombre,estado,fechaalta,usuarioalta)
values ('ING','INGRESO',1,getdate(),'SQL Init')
insert into rubros_cuentas (codigo,nombre,estado,fechaalta,usuarioalta)
values ('EFR','EGRESO',1,getdate(),'SQL Init')