insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('DP','DEVOLUCION A PROVEEDOR',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('EM','ENTRADA MATERIA PRIMA',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('DF','ENTRADA POR DEVOLUCION FASON',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('NE','NOTA DE ENTRADA',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('NS','NOTA DE SALIDA',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('RP','REMITO DE PROVEEDOR',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('RI','REMITO INTERNO',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SM','SALIDA DE MATERIA PRIMA',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('TR','TRANSFORMACION',1,getdate(),'SQL Init')
insert into TipoMotivos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PR','PRESUPUESTO',1,getdate(),'SQL Init')

