declare @paisid int =(select id from Paises where codigo ='ARG')

insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CABA',LTRIM(RTRIM('  Buenos Aires')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CATA',LTRIM(RTRIM('  Catamarca')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CHA',LTRIM(RTRIM('  Chaco')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CHU',LTRIM(RTRIM('  Chubut')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('COR',LTRIM(RTRIM('  Córdoba')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CORR',LTRIM(RTRIM('  Corrientes')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('ERIOS',LTRIM(RTRIM('  Entre Ríos')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('FOR',LTRIM(RTRIM('  Formosa')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('JUJ',LTRIM(RTRIM('  Jujuy')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('LAPAMP',LTRIM(RTRIM('  La Pampa')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('LARIO',LTRIM(RTRIM('  La Rioja')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('MEN',LTRIM(RTRIM('  Mendoza')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('MIS',LTRIM(RTRIM('  Misiones')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('NEU',LTRIM(RTRIM('  Neuquén')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('RNEGRO',LTRIM(RTRIM('  Río Negro')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SAL',LTRIM(RTRIM('  Salta')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANJ',LTRIM(RTRIM('  San Juan')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANL',LTRIM(RTRIM('  San Luis')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANTAC',LTRIM(RTRIM('  Santa Cruz')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANTAF',LTRIM(RTRIM('  Santa Fe')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SGOEST',LTRIM(RTRIM('  Santiago del Estero')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('TFUEGO',LTRIM(RTRIM('  Tierra del Fuego')),@paisid,getdate(),'Admin',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('TUC',LTRIM(RTRIM('  Tucumán')),@paisid,getdate(),'Admin',1)
