insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (1008,'WHITE',20336,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (910,'BLANCO',20338,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (959,'MIEL',20339,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (140,'OBISPO',20341,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (218,'CAPPUCCINO',20344,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (184,'CARAMEL',20345,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (285,'NUDE',20348,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (183,'NUDE',20349,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (284,'ROUGE',20350,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (380,'NARANJA',20354,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (532,'AZUL',20361,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (529,'CAMEL',20362,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (530,'CORAL',20363,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (531,'NARANJA',20364,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (576,'VERDE',20368,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (537,'VISON',20369,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (705,'BISCOTTI',20371,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (706,'BLANCO',20372,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (704,'CORAL',20374,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (703,'OCEAN',20376,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (55,'PIPER',20379,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (410,'CORAL',20380,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (954,'VAQUETA',20381,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (409,'VERDE',20382,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (230,'AZUL',20383,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (194,'PAPRICA(CORAL)',20384,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (689,'CORAL',20386,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (652,'TAN/C/MAGIC',20392,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (651,'NEGRO/C/KATE',20393,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (973,'NARANJA',20408,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (974,'NATURAL',20409,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (692,'PLATA',20416,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (691,'PLATINO',20417,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (295,'.NEGRO',20418,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (345,'MARRON',20420,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (490,'CHOCOLATE',20423,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (492,'MUSGO',20424,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (491,'VISON',20426,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (719,'AZUL',20431,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (597,'NATURAL',20432,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (293,'ROUGE',20435,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (328,'BORDO',20436,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (326,'NUEZ',20437,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (32,'CYTRUS',20441,146,1,getdate(),'admin')
insert into colores (Codigo,Descripcion,InsumoId,TemporadaId,Estado,FechaAlta,UsuarioAlta)
values (30,'DENIM',20442,146,1,getdate(),'admin')
