declare @paisid int =(select id from Paises where codigo ='ARG')

insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CABA',LTRIM(RTRIM('Buenos Aires')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CATA',LTRIM(RTRIM('Catamarca')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CHA',LTRIM(RTRIM('Chaco')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CHU',LTRIM(RTRIM('Chubut')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('COR',LTRIM(RTRIM('Córdoba')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('CORR',LTRIM(RTRIM('Corrientes')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('ERIOS',LTRIM(RTRIM('Entre Ríos')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('FOR',LTRIM(RTRIM('Formosa')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('JUJ',LTRIM(RTRIM('Jujuy')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('LAPAMP',LTRIM(RTRIM('La Pampa')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('LARIO',LTRIM(RTRIM('La Rioja')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('MEN',LTRIM(RTRIM('Mendoza')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('MIS',LTRIM(RTRIM('Misiones')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('NEU',LTRIM(RTRIM('Neuquén')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('RNEGRO',LTRIM(RTRIM('Río Negro')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SAL',LTRIM(RTRIM('Salta')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANJ',LTRIM(RTRIM('San Juan')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANL',LTRIM(RTRIM('San Luis')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANTAC',LTRIM(RTRIM('Santa Cruz')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SANTAF',LTRIM(RTRIM('Santa Fe')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SGOEST',LTRIM(RTRIM('Santiago del Estero')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('TFUEGO',LTRIM(RTRIM('Tierra del Fuego')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('TUC',LTRIM(RTRIM('Tucumán')),@paisid,getdate(),'SQL Init',1)
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SDARG',LTRIM(RTRIM('SIN DEFINIR')),@paisid,getdate(),'SQL Init',1)


SET @paisid  =(select id from Paises where codigo ='CHI')
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SDCHI','SIN DEFINIR',@paisid,getdate(),'SQL Init',1)


SET @paisid  =(select id from Paises where codigo ='EEUU')
insert into Provincias (codigo,Descripcion,PaisId,FechaAlta,UsuarioAlta,Estado)
values('SDEEUU','SIN DEFINIR',@paisid,getdate(),'SQL Init',1)
