declare @AnoTemporada int = 2010
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2011
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2012
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2013
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2014
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2015
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2016
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
set @AnoTemporada = 2017
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('IV'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno - Verano ' + STR(@AnoTemporada),'01/01/'+STR(@AnoTemporada),'31/12/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('I'+CAST(@AnoTemporada as nvarchar(100)))),'Invierno  ' + STR(@AnoTemporada),'25/02/'+STR(@AnoTemporada),'15/08/'+STR(@AnoTemporada),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values(LTRIM(RTRIM('V'+CAST(@AnoTemporada as nvarchar(100)))),LTRIM(RTRIM('Verano ' + STR(@AnoTemporada) +' - ' +STR(@AnoTemporada+ 1))),'16/08/'+STR(@AnoTemporada),'24/02/'+STR(@AnoTemporada+1),1,getdate(),'SQL Init')
insert into temporadas (Codigo,descripcion,FechaDesde,FechaHasta,Estado,FechaAlta,UsuarioAlta)
values ('SD','SIN DEFINIR','01/01/1900','01/01/2100',1,getdate(),'SQL Init')
