insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0007','COMISIONES',1,getdate(),'SQL Init',1200,28)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0002','HONORARIOS PROFESIONALES',1,getdate(),'SQL Init',1200,28)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0004','INTERESES POR FINANCIAMIENTO',1,getdate(),'SQL Init',11242.7,0.5)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0006','SERVICIOS',1,getdate(),'SQL Init',5000,2)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0010','SIN RETENCIONES',1,getdate(),'SQL Init',999999999.99,0.01)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0001','VENTA DE BIENES DE CAMBIO',1,getdate(),'SQL Init',1200,2)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0003','ALQUILERES',1,getdate(),'SQL Init',1200,6)
insert into Retenciones (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,MinimoNoImponible,Alicuota)
values ('0005','CHEQUE RECHAZADO S/GASTOS',1,getdate(),'SQL Init',0,0)
