/*Alta de talles*/
DECLARE @CatTalleId int = (select id from CategoriaTalles where codigo = 'TZ')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (35,'Talle 35',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (36,'Talle 36',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (37,'Talle 37',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (38,'Talle 38',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (39,'Talle 39',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (40,'Talle 40',1,getdate(),'SQL Init',@CatTalleId)
set @CatTalleId = (select id from CategoriaTalles where codigo = 'CP')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (1,'Talle 1',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (2,'Talle 2',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (3,'Talle 3',1,getdate(),'SQL Init',@CatTalleId)
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (4,'Talle 4',1,getdate(),'SQL Init',@CatTalleId)
set @CatTalleId = (select id from CategoriaTalles where codigo = 'U')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta,CategoriaTalleId)
values (0,'Talle Unico',1,getdate(),'SQL Init',@CatTalleId)