
insert into Atributos (Codigo,Descripcion,padreid,Estado,FechaAlta,UsuarioAlta)
values ('CAR','Cartera',1,1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BAN','Bandolera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('SHO','Shopping',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('SOB','Sobre',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MOR','Morral',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('GOL','Golfera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolso',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MOC','Mochila',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BAU','Baul',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BAL','Balde',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MAR','Marinero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CAL','Calzado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('ZAP','Zapatos',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOT','Bota',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('STIL','Stileto',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOR','Borcego',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('SAN','Sandalia',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BTN','Botineta',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('OJO','Ojota',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MOC','Mocasin',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('TEJ','Tejana',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PAN','Pancha',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BAL','Balerina',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('ZPT','Zapatilla',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('ABO','Abotinado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('ROC','Rock',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PUL','Pulsera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('REL','Relojes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PAS','Pashimnas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PAR','Paraguas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('COR','Corto',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('LAR','Largo',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CIN','Cinturon',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('EQU','Equipaje',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolso',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('VAL','Valija',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOC','Bols con carro',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BIL','Billeteras',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('DMA','Dama',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('HMB','Hombre',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('LLA','Llavero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PRE','Prendas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('TAP','Tapado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BLA','Blaizer',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('SAC','Saco',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PRK','Parka',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CAM','Campera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CHA','Chaleco',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PIE','Piel sintetico',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CAR','Cardigan',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('SWE','Sweater',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PON','Poncho',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PER','Perfumes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('ACC','Accesorio',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MON','Monedero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('POL','Porta lentes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolsas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CRN','Carton',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('POL','Polietileno',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('FRI','Frizelina',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('GRA','Graficas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CAJ','Cajas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('MAD','Madera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('PLA','Plastico',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,PadreId,Estado,FechaAlta,UsuarioAlta)
values ('CRN','Carton',1,GETDATE(),'Admin')
/*Ver mail enviado a ivan 02/04/2016 para modificar tabla atributos*/
select * from insumos
select * from articulos
select * from Colores