delete from CategoriaAtributo
delete from CategoriaTalles
delete from talles
/*Alta de Categoria de talles*/
insert into CategoriaTalles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('TZ','Tarea de zapatos',1,getdate(),'Admin')
insert into CategoriaTalles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CP','Curva de prendas',1,getdate(),'Admin')
insert into CategoriaTalles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('U','Talle Unico',1,getdate(),'Admin')
/*Alta de talles*/
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (35,'Talle 35',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (36,'Talle 36',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (37,'Talle 37',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (38,'Talle 38',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (39,'Talle 39',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (40,'Talle 40',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (1,'Talle 1',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (2,'Talle 2',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (3,'Talle 3',1,getdate(),'Admin')
insert into talles (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values (0,'Talle Unico',1,getdate(),'Admin')
/*Alta de Categoria atributo*/
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,7,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,8,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,9,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,10,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,11,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (2,12,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (3,13,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (3,14,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (3,15,1,GETDATE(),'Admin')
insert into CategoriaAtributo (CategoriaTalleId,TalleId,Estado,FechaAlta,UsuarioAlta)
values (4,16,1,GETDATE(),'Admin')
/*-------------------------------------------------------------------------------------------------*/
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CAR','Cartera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BAN','Bandolera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SHO','Shopping',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SOB','Sobre',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MOR','Morral',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('GOL','Golfera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolso',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MOC','Mochila',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BAU','Baul',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BAL','Balde',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MAR','Marinero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CAL','Calzado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('ZAP','Zapatos',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOT','Bota',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('STIL','Stileto',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOR','Borcego',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SAN','Sandalia',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BTN','Botineta',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('OJO','Ojota',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MOC','Mocasin',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('TEJ','Tejana',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PAN','Pancha',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BAL','Balerina',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('ZPT','Zapatilla',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('ABO','Abotinado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('ROC','Rock',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PUL','Pulsera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('REL','Relojes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PAS','Pashimnas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PAR','Paraguas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('COR','Corto',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('LAR','Largo',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CIN','Cinturon',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('EQU','Equipaje',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolso',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('VAL','Valija',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOC','Bols con carro',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BIL','Billeteras',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('DMA','Dama',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('HMB','Hombre',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('LLA','Llavero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PRE','Prendas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('TAP','Tapado',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BLA','Blaizer',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SAC','Saco',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PRK','Parka',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CAM','Campera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CHA','Chaleco',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PIE','Piel sintetico',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CAR','Cardigan',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('SWE','Sweater',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PON','Poncho',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PER','Perfumes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('ACC','Accesorio',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MON','Monedero',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('POL','Porta lentes',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('BOL','Bolsas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CRN','Carton',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('POL','Polietileno',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('FRI','Frizelina',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('GRA','Graficas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CAJ','Cajas',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('MAD','Madera',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('PLA','Plastico',1,GETDATE(),'Admin')
insert into Atributos (Codigo,Descripcion,Estado,FechaAlta,UsuarioAlta)
values ('CRN','Carton',1,GETDATE(),'Admin')
/*Ver mail enviado a ivan 02/04/2016 para modificar tabla atributos*/

select * from articulos
select * from Colores